### ISSUE TITLE
installation of the gem fails. plugin can't be found

### ISSUE THREAD

**Issue by B1tMaster** [y-ken/fluent-plugin-anonymizer#17]
gem install fluent-plugin-anonymizer

ERROR:  Could not find a valid gem 'fluent-plugin-anonymizer' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/specs.4.8.gz)

Any suggestions?
Thank you!
-D.

**Comment by y-ken** [comment]
Can you get the specs file correctly? If it fails, your ssl pem file should be update.
```
$ wget https://rubygems.org/specs.4.8.gz
# or
$ curl https://rubygems.org/specs.4.8.gz -o specs.4.8.gz
```

If you got the error, add non ssl rubygems with following instruction.

```
$ gem source --add http://rubygems.org
https://rubygems.org is recommended for security over http://rubygems.org

Do you want to add this insecure source? [yn]  y
$ gem install rubygems-update
$ gem source --remove http://rubygems.org

# finally, you will get install it.
$ gem install fluent-plugin-anonymizer```

**Comment by B1tMaster** [comment]
Thank you very much for pointers!

I found a problem in my machine. It was a a disabled proxy which should have been enabled.

Regards,
-D.

**Comment by y-ken** [comment]
Sounds great to hear from you that.
