### ISSUE TITLE
Is <mask ARGUMENT> style easy to mistake?

### ISSUE THREAD

**Issue by okkez** [y-ken/fluent-plugin-anonymizer#27]
Copied from #25 

@y-ken said:

----
I suggest `<mask>` section won't have ARGUMENT like `<mask ARGUMENT>`.
Because It does not often used section which have argument as like of other plugins.
In other point of view, It can be mistake to masking `network` key when using`<mask network>` style.
How do you think about this?

I suggest this style. It is hard to mistake setting mask type.
```
  <mask>
    type sha1
    keys user_id, member_id, mail
    # Set hash salt with any strings for more security
    salt mysaltstring
  </mask>
```

Current sample is below.

```
  <mask sha1>
    keys user_id, member_id, mail
    # Set hash salt with any strings for more security
    salt mysaltstring
  </mask>
```

----

@y-ken 
In v0.14/v1, buffer configuration is also using argument to specify `chunk_keys`:
https://docs.fluentd.org/v1.0/articles/buffer-section#chunk-keys
I think that this arguments feature is not well known feature, though...

**Comment by okkez** [comment]
`<mask ARGUMENT>` style's ARGUMENT is required. So we cannot forget to add ARGUMENT.
And ARGUMENT is enum type, so we cannot specify wrong type argument.

On the other hand, `type sha1` is similar to `@type` parameter like `<match>`, `<filter>`, `<parse>`, and etc.
It is confusing for me to use `type sha1` style in `<mask>` section. Is leading `@` required or not ...?

**Comment by y-ken** [comment]
> It is confusing for me to use type sha1 style in <mask> section. Is leading @ required or not ...?

Yes. exactly.

**Comment by y-ken** [comment]
Thank you for our discussion. It is no problem. I've got it.
