### ISSUE TITLE
Implementing a filter plugin support

### ISSUE THREAD

**Issue by kiyoto** [y-ken/fluent-plugin-anonymizer#6]
This plugin is a great example of a useful output plugin that should really be a filter plugin. I suggest that

1. the anonymization functionality is factored out into a re-usable library used both by the existing `out_anonymizer.rb` and `filter_anonymizer.rb`
2. Implement the filter plugin version (`filter_anonymizer`)

**Comment by y-ken** [comment]
#8 has done! :beers:
