### ISSUE TITLE
Support label feature

### ISSUE THREAD

**Issue by cosmo0920** [y-ken/fluent-plugin-anonymizer#9]
This plugin seems to be using `Fluent::Engine.emit`.
It should be using `router.emit` instead.

I'll start to work this a bit of improvement after #8 is merged.

**Comment by y-ken** [comment]
Nice!

**Comment by y-ken** [comment]
Hi @cosmo0920 
#8 has merged. So, it comes the time to implement.
Would you please add label feature?

**Comment by cosmo0920** [comment]
OK. I'll try it.

**Comment by cosmo0920** [comment]
#10 is merged.
